// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbAccess

import (
	"database/sql"
)

type AiBatch struct {
	ID                int64
	ProviderBatchID   string
	Status            string
	RequestCount      sql.NullInt64
	SubmittedAtUnix   int64
	LastCheckedAtUnix sql.NullInt64
	CompletedAtUnix   sql.NullInt64
	RawJson           sql.NullString
}

type AiRequest struct {
	ID            int64
	ImageFileID   int64
	BatchID       sql.NullInt64
	CustomID      string
	Model         string
	Status        string
	Error         sql.NullString
	CreatedAtUnix int64
	UpdatedAtUnix sql.NullInt64
}

type AiResult struct {
	ID            int64
	RequestID     int64
	OutputJson    string
	CreatedAtUnix int64
}

type ImageFile struct {
	ID            int64
	File          string
	Name          string
	Ext           string
	Url           sql.NullString
	SizeBytes     sql.NullInt64
	MtimeUnix     sql.NullInt64
	Status        string
	LastError     sql.NullString
	Description   sql.NullString
	CreatedAtUnix int64
	UpdatedAtUnix int64
}

type ImageMetum struct {
	ID   int64
	Meta string
}

type MetaMap struct {
	ImageFileID int64
	ImageMetaID int64
}
