// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbAccess

import (
	"database/sql"
)

type ImageFile struct {
	ID            int64
	File          string
	Name          string
	Ext           string
	Url           sql.NullString
	SizeBytes     sql.NullInt64
	MtimeUnix     sql.NullInt64
	Status        string
	LastError     sql.NullString
	CreatedAtUnix int64
	UpdatedAtUnix int64
}

type ImageMetum struct {
	ID   int64
	Meta string
}

type MetaMap struct {
	ImageFileID int64
	ImageMetaID int64
}

type OpenaiBatch struct {
	ID                int64
	OpenaiBatchID     string
	InputFileID       string
	OutputFileID      sql.NullString
	ErrorFileID       sql.NullString
	Endpoint          string
	Status            string
	RequestCount      sql.NullInt64
	SubmittedAtUnix   int64
	LastCheckedAtUnix sql.NullInt64
	CompletedAtUnix   sql.NullInt64
	RawJson           sql.NullString
}

type OpenaiRequest struct {
	ID            int64
	ImageFileID   int64
	BatchID       sql.NullInt64
	CustomID      string
	Model         string
	Status        string
	Error         sql.NullString
	CreatedAtUnix int64
	UpdatedAtUnix sql.NullInt64
}

type OpenaiResult struct {
	ID            int64
	RequestID     int64
	OutputJson    string
	CreatedAtUnix int64
}
