// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbAccess

import (
	"context"
	"database/sql"
)

const attachRequestsToBatch = `-- name: AttachRequestsToBatch :exec
UPDATE openai_request SET batch_id = ?, status = 'submitted', updated_at_unix = ? WHERE status = 'queued' AND batch_id IS NULL
`

type AttachRequestsToBatchParams struct {
	BatchID       sql.NullInt64
	UpdatedAtUnix sql.NullInt64
}

func (q *Queries) AttachRequestsToBatch(ctx context.Context, arg AttachRequestsToBatchParams) error {
	_, err := q.db.ExecContext(ctx, attachRequestsToBatch, arg.BatchID, arg.UpdatedAtUnix)
	return err
}

const deleteMetaMapForImage = `-- name: DeleteMetaMapForImage :exec
DELETE FROM meta_map WHERE image_file_id = ?
`

func (q *Queries) DeleteMetaMapForImage(ctx context.Context, imageFileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMetaMapForImage, imageFileID)
	return err
}

const getActiveBatches = `-- name: GetActiveBatches :many
SELECT id, openai_batch_id, input_file_id, output_file_id, error_file_id, endpoint, status, request_count, submitted_at_unix, last_checked_at_unix, completed_at_unix, raw_json FROM openai_batch WHERE status NOT IN ('completed', 'failed', 'expired', 'cancelled') ORDER BY id
`

func (q *Queries) GetActiveBatches(ctx context.Context) ([]OpenaiBatch, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenaiBatch
	for rows.Next() {
		var i OpenaiBatch
		if err := rows.Scan(
			&i.ID,
			&i.OpenaiBatchID,
			&i.InputFileID,
			&i.OutputFileID,
			&i.ErrorFileID,
			&i.Endpoint,
			&i.Status,
			&i.RequestCount,
			&i.SubmittedAtUnix,
			&i.LastCheckedAtUnix,
			&i.CompletedAtUnix,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, openai_batch_id, input_file_id, output_file_id, error_file_id, endpoint, status, request_count, submitted_at_unix, last_checked_at_unix, completed_at_unix, raw_json FROM openai_batch WHERE id = ?
`

func (q *Queries) GetBatchByID(ctx context.Context, id int64) (OpenaiBatch, error) {
	row := q.db.QueryRowContext(ctx, getBatchByID, id)
	var i OpenaiBatch
	err := row.Scan(
		&i.ID,
		&i.OpenaiBatchID,
		&i.InputFileID,
		&i.OutputFileID,
		&i.ErrorFileID,
		&i.Endpoint,
		&i.Status,
		&i.RequestCount,
		&i.SubmittedAtUnix,
		&i.LastCheckedAtUnix,
		&i.CompletedAtUnix,
		&i.RawJson,
	)
	return i, err
}

const getBatchByOpenAIID = `-- name: GetBatchByOpenAIID :one
SELECT id, openai_batch_id, input_file_id, output_file_id, error_file_id, endpoint, status, request_count, submitted_at_unix, last_checked_at_unix, completed_at_unix, raw_json FROM openai_batch WHERE openai_batch_id = ?
`

func (q *Queries) GetBatchByOpenAIID(ctx context.Context, openaiBatchID string) (OpenaiBatch, error) {
	row := q.db.QueryRowContext(ctx, getBatchByOpenAIID, openaiBatchID)
	var i OpenaiBatch
	err := row.Scan(
		&i.ID,
		&i.OpenaiBatchID,
		&i.InputFileID,
		&i.OutputFileID,
		&i.ErrorFileID,
		&i.Endpoint,
		&i.Status,
		&i.RequestCount,
		&i.SubmittedAtUnix,
		&i.LastCheckedAtUnix,
		&i.CompletedAtUnix,
		&i.RawJson,
	)
	return i, err
}

const getImageFileByID = `-- name: GetImageFileByID :one
SELECT id, file, name, ext, url, size_bytes, mtime_unix, status, last_error, created_at_unix, updated_at_unix FROM image_file WHERE id = ?
`

func (q *Queries) GetImageFileByID(ctx context.Context, id int64) (ImageFile, error) {
	row := q.db.QueryRowContext(ctx, getImageFileByID, id)
	var i ImageFile
	err := row.Scan(
		&i.ID,
		&i.File,
		&i.Name,
		&i.Ext,
		&i.Url,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Status,
		&i.LastError,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getImageFileByPath = `-- name: GetImageFileByPath :one
SELECT id, file, name, ext, url, size_bytes, mtime_unix, status, last_error, created_at_unix, updated_at_unix FROM image_file WHERE file = ?
`

func (q *Queries) GetImageFileByPath(ctx context.Context, file string) (ImageFile, error) {
	row := q.db.QueryRowContext(ctx, getImageFileByPath, file)
	var i ImageFile
	err := row.Scan(
		&i.ID,
		&i.File,
		&i.Name,
		&i.Ext,
		&i.Url,
		&i.SizeBytes,
		&i.MtimeUnix,
		&i.Status,
		&i.LastError,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getImageMetaByText = `-- name: GetImageMetaByText :one
SELECT id FROM image_meta WHERE meta = ?
`

func (q *Queries) GetImageMetaByText(ctx context.Context, meta string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getImageMetaByText, meta)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMetaForImage = `-- name: GetMetaForImage :many
SELECT im.meta FROM image_meta im
JOIN meta_map mm ON im.id = mm.image_meta_id
WHERE mm.image_file_id = ?
`

func (q *Queries) GetMetaForImage(ctx context.Context, imageFileID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMetaForImage, imageFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var meta string
		if err := rows.Scan(&meta); err != nil {
			return nil, err
		}
		items = append(items, meta)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingImages = `-- name: GetPendingImages :many
SELECT id, file, name, ext, url, size_bytes, mtime_unix, status, last_error, created_at_unix, updated_at_unix FROM image_file WHERE status IN ('new', 'error') ORDER BY id
`

func (q *Queries) GetPendingImages(ctx context.Context) ([]ImageFile, error) {
	rows, err := q.db.QueryContext(ctx, getPendingImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageFile
	for rows.Next() {
		var i ImageFile
		if err := rows.Scan(
			&i.ID,
			&i.File,
			&i.Name,
			&i.Ext,
			&i.Url,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.Status,
			&i.LastError,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuedImages = `-- name: GetQueuedImages :many
SELECT id, file, name, ext, url, size_bytes, mtime_unix, status, last_error, created_at_unix, updated_at_unix FROM image_file WHERE status = 'queued' ORDER BY id
`

func (q *Queries) GetQueuedImages(ctx context.Context) ([]ImageFile, error) {
	rows, err := q.db.QueryContext(ctx, getQueuedImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageFile
	for rows.Next() {
		var i ImageFile
		if err := rows.Scan(
			&i.ID,
			&i.File,
			&i.Name,
			&i.Ext,
			&i.Url,
			&i.SizeBytes,
			&i.MtimeUnix,
			&i.Status,
			&i.LastError,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuedRequests = `-- name: GetQueuedRequests :many
SELECT id, image_file_id, batch_id, custom_id, model, status, error, created_at_unix, updated_at_unix FROM openai_request WHERE status = 'queued' AND batch_id IS NULL ORDER BY id
`

func (q *Queries) GetQueuedRequests(ctx context.Context) ([]OpenaiRequest, error) {
	rows, err := q.db.QueryContext(ctx, getQueuedRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenaiRequest
	for rows.Next() {
		var i OpenaiRequest
		if err := rows.Scan(
			&i.ID,
			&i.ImageFileID,
			&i.BatchID,
			&i.CustomID,
			&i.Model,
			&i.Status,
			&i.Error,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestByCustomID = `-- name: GetRequestByCustomID :one
SELECT id, image_file_id, batch_id, custom_id, model, status, error, created_at_unix, updated_at_unix FROM openai_request WHERE custom_id = ?
`

func (q *Queries) GetRequestByCustomID(ctx context.Context, customID string) (OpenaiRequest, error) {
	row := q.db.QueryRowContext(ctx, getRequestByCustomID, customID)
	var i OpenaiRequest
	err := row.Scan(
		&i.ID,
		&i.ImageFileID,
		&i.BatchID,
		&i.CustomID,
		&i.Model,
		&i.Status,
		&i.Error,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, image_file_id, batch_id, custom_id, model, status, error, created_at_unix, updated_at_unix FROM openai_request WHERE id = ?
`

func (q *Queries) GetRequestByID(ctx context.Context, id int64) (OpenaiRequest, error) {
	row := q.db.QueryRowContext(ctx, getRequestByID, id)
	var i OpenaiRequest
	err := row.Scan(
		&i.ID,
		&i.ImageFileID,
		&i.BatchID,
		&i.CustomID,
		&i.Model,
		&i.Status,
		&i.Error,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getRequestsForBatch = `-- name: GetRequestsForBatch :many
SELECT id, image_file_id, batch_id, custom_id, model, status, error, created_at_unix, updated_at_unix FROM openai_request WHERE batch_id = ?
`

func (q *Queries) GetRequestsForBatch(ctx context.Context, batchID sql.NullInt64) ([]OpenaiRequest, error) {
	rows, err := q.db.QueryContext(ctx, getRequestsForBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenaiRequest
	for rows.Next() {
		var i OpenaiRequest
		if err := rows.Scan(
			&i.ID,
			&i.ImageFileID,
			&i.BatchID,
			&i.CustomID,
			&i.Model,
			&i.Status,
			&i.Error,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultByRequestID = `-- name: GetResultByRequestID :one
SELECT id, request_id, output_json, created_at_unix FROM openai_result WHERE request_id = ?
`

func (q *Queries) GetResultByRequestID(ctx context.Context, requestID int64) (OpenaiResult, error) {
	row := q.db.QueryRowContext(ctx, getResultByRequestID, requestID)
	var i OpenaiResult
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OutputJson,
		&i.CreatedAtUnix,
	)
	return i, err
}

const insertBatch = `-- name: InsertBatch :one

INSERT INTO openai_batch (openai_batch_id, input_file_id, endpoint, status, request_count, submitted_at_unix, raw_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBatchParams struct {
	OpenaiBatchID   string
	InputFileID     string
	Endpoint        string
	Status          string
	RequestCount    sql.NullInt64
	SubmittedAtUnix int64
	RawJson         sql.NullString
}

// ============================================================================
// OpenAI Batch Queries
// ============================================================================
func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBatch,
		arg.OpenaiBatchID,
		arg.InputFileID,
		arg.Endpoint,
		arg.Status,
		arg.RequestCount,
		arg.SubmittedAtUnix,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImageFile = `-- name: InsertImageFile :one

INSERT INTO image_file (file, name, ext, url, size_bytes, mtime_unix, status, created_at_unix, updated_at_unix)
VALUES (?, ?, ?, ?, ?, ?, 'new', ?, ?)
ON CONFLICT(file) DO UPDATE SET
    url = excluded.url,
    size_bytes = excluded.size_bytes,
    mtime_unix = excluded.mtime_unix,
    updated_at_unix = excluded.updated_at_unix
RETURNING id
`

type InsertImageFileParams struct {
	File          string
	Name          string
	Ext           string
	Url           sql.NullString
	SizeBytes     sql.NullInt64
	MtimeUnix     sql.NullInt64
	CreatedAtUnix int64
	UpdatedAtUnix int64
}

// ============================================================================
// Image File Queries
// ============================================================================
func (q *Queries) InsertImageFile(ctx context.Context, arg InsertImageFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertImageFile,
		arg.File,
		arg.Name,
		arg.Ext,
		arg.Url,
		arg.SizeBytes,
		arg.MtimeUnix,
		arg.CreatedAtUnix,
		arg.UpdatedAtUnix,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImageMeta = `-- name: InsertImageMeta :one

INSERT OR IGNORE INTO image_meta (meta)
VALUES (?)
RETURNING id
`

// ============================================================================
// Image Meta Queries
// ============================================================================
func (q *Queries) InsertImageMeta(ctx context.Context, meta string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertImageMeta, meta)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMetaMap = `-- name: InsertMetaMap :exec
INSERT OR IGNORE INTO meta_map (image_file_id, image_meta_id)
VALUES (?, ?)
`

type InsertMetaMapParams struct {
	ImageFileID int64
	ImageMetaID int64
}

func (q *Queries) InsertMetaMap(ctx context.Context, arg InsertMetaMapParams) error {
	_, err := q.db.ExecContext(ctx, insertMetaMap, arg.ImageFileID, arg.ImageMetaID)
	return err
}

const insertRequest = `-- name: InsertRequest :one

INSERT INTO openai_request (image_file_id, custom_id, model, status, created_at_unix)
VALUES (?, ?, ?, 'queued', ?)
RETURNING id
`

type InsertRequestParams struct {
	ImageFileID   int64
	CustomID      string
	Model         string
	CreatedAtUnix int64
}

// ============================================================================
// OpenAI Request Queries
// ============================================================================
func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRequest,
		arg.ImageFileID,
		arg.CustomID,
		arg.Model,
		arg.CreatedAtUnix,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertResult = `-- name: InsertResult :one

INSERT INTO openai_result (request_id, output_json, created_at_unix)
VALUES (?, ?, ?)
RETURNING id
`

type InsertResultParams struct {
	RequestID     int64
	OutputJson    string
	CreatedAtUnix int64
}

// ============================================================================
// OpenAI Result Queries
// ============================================================================
func (q *Queries) InsertResult(ctx context.Context, arg InsertResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertResult, arg.RequestID, arg.OutputJson, arg.CreatedAtUnix)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markImagesQueued = `-- name: MarkImagesQueued :exec
UPDATE image_file SET status = 'queued', updated_at_unix = ? WHERE status = 'new'
`

func (q *Queries) MarkImagesQueued(ctx context.Context, updatedAtUnix int64) error {
	_, err := q.db.ExecContext(ctx, markImagesQueued, updatedAtUnix)
	return err
}

const updateBatchCompleted = `-- name: UpdateBatchCompleted :exec
UPDATE openai_batch SET status = 'completed', output_file_id = ?, error_file_id = ?, completed_at_unix = ?, last_checked_at_unix = ?, raw_json = ? WHERE id = ?
`

type UpdateBatchCompletedParams struct {
	OutputFileID      sql.NullString
	ErrorFileID       sql.NullString
	CompletedAtUnix   sql.NullInt64
	LastCheckedAtUnix sql.NullInt64
	RawJson           sql.NullString
	ID                int64
}

func (q *Queries) UpdateBatchCompleted(ctx context.Context, arg UpdateBatchCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchCompleted,
		arg.OutputFileID,
		arg.ErrorFileID,
		arg.CompletedAtUnix,
		arg.LastCheckedAtUnix,
		arg.RawJson,
		arg.ID,
	)
	return err
}

const updateBatchFailed = `-- name: UpdateBatchFailed :exec
UPDATE openai_batch SET status = ?, error_file_id = ?, last_checked_at_unix = ?, raw_json = ? WHERE id = ?
`

type UpdateBatchFailedParams struct {
	Status            string
	ErrorFileID       sql.NullString
	LastCheckedAtUnix sql.NullInt64
	RawJson           sql.NullString
	ID                int64
}

func (q *Queries) UpdateBatchFailed(ctx context.Context, arg UpdateBatchFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchFailed,
		arg.Status,
		arg.ErrorFileID,
		arg.LastCheckedAtUnix,
		arg.RawJson,
		arg.ID,
	)
	return err
}

const updateBatchStatus = `-- name: UpdateBatchStatus :exec
UPDATE openai_batch SET status = ?, last_checked_at_unix = ? WHERE id = ?
`

type UpdateBatchStatusParams struct {
	Status            string
	LastCheckedAtUnix sql.NullInt64
	ID                int64
}

func (q *Queries) UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchStatus, arg.Status, arg.LastCheckedAtUnix, arg.ID)
	return err
}

const updateImageFileError = `-- name: UpdateImageFileError :exec
UPDATE image_file SET status = 'error', last_error = ?, updated_at_unix = ? WHERE id = ?
`

type UpdateImageFileErrorParams struct {
	LastError     sql.NullString
	UpdatedAtUnix int64
	ID            int64
}

func (q *Queries) UpdateImageFileError(ctx context.Context, arg UpdateImageFileErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateImageFileError, arg.LastError, arg.UpdatedAtUnix, arg.ID)
	return err
}

const updateImageFileStatus = `-- name: UpdateImageFileStatus :exec
UPDATE image_file SET status = ?, updated_at_unix = ? WHERE id = ?
`

type UpdateImageFileStatusParams struct {
	Status        string
	UpdatedAtUnix int64
	ID            int64
}

func (q *Queries) UpdateImageFileStatus(ctx context.Context, arg UpdateImageFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImageFileStatus, arg.Status, arg.UpdatedAtUnix, arg.ID)
	return err
}

const updateRequestCompleted = `-- name: UpdateRequestCompleted :exec
UPDATE openai_request SET status = 'completed', updated_at_unix = ? WHERE id = ?
`

type UpdateRequestCompletedParams struct {
	UpdatedAtUnix sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateRequestCompleted(ctx context.Context, arg UpdateRequestCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestCompleted, arg.UpdatedAtUnix, arg.ID)
	return err
}

const updateRequestError = `-- name: UpdateRequestError :exec
UPDATE openai_request SET status = 'error', error = ?, updated_at_unix = ? WHERE id = ?
`

type UpdateRequestErrorParams struct {
	Error         sql.NullString
	UpdatedAtUnix sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateRequestError(ctx context.Context, arg UpdateRequestErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestError, arg.Error, arg.UpdatedAtUnix, arg.ID)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE openai_request SET status = ?, updated_at_unix = ? WHERE id = ?
`

type UpdateRequestStatusParams struct {
	Status        string
	UpdatedAtUnix sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestStatus, arg.Status, arg.UpdatedAtUnix, arg.ID)
	return err
}
